### ISSUE TITLE
Strange behaviour after renaming a file. 

### ISSUE THREAD

**Issue by trungleduc** [jupyterlab/jupyter-collaboration#165]
## Description

I had strange behaviors in a brand new environment with `jupyterlab 4.0.2` and `jupyter_collaboration 1.0.0`

- Creating a new notebook takes some seconds to get the file displayed in the file browser.
- Rename a file then close it, create a new file then the name of the previous file is shown in the tab title.

## Reproduce

https://github.com/jupyterlab/jupyter_collaboration/assets/4451292/1b031987-26b2-4e38-aac2-de9870ecbada

## Context

- Operating System and version: Windows 11
- Browser and version: Firefox 114.0.1 
- JupyterLab version: 4.0.2

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by fcollonval** [comment]
I can confirm that bug - I saw it too when working to migrate the documents example.

The worst is that if you delete the file (like test.ipynb) and restart jupyterlab (close and start the server), the new file will still be renamed with that old name. I tried removing the file ID db but it did not help (I may have done something wrong here).

**Comment by davidbrochart** [comment]
FYI this doesn't seem to happen with Jupyverse.

**Comment by hbcarlos** [comment]
We also need https://github.com/jupyterlab/jupyterlab/pull/14771 to fix this issue.
