### ISSUE TITLE
"RTC:" Prefix in Filename URL

### ISSUE THREAD

**Issue by la0bing** [jupyterlab/jupyter-collaboration#183]
## Description

With both `jupyter-collaboration` and `jupyter_scheduler` extensions installed, `jupyter_scheduler` will detect `notebook.ipynb` as `RTC:notebook.ipynb` which causes `jupyter_scheduler` failing to find the file in path, the file path URL will also look something like this: "localhost:8080/user/user1/lab/tree/RTC%3Anotebook.ipynb"

Weirdly I also noticed "RTC:" in the launcher tab as well.

## Reproduce

1. Install the following libraries in Python 3.11.4
```
conda install jupyter-collaboration=1.0.1
pip install jupyter_scheduler==2.0.0 jupyterlab==4.0.4
```
2. Start jupyterlab with
```
jupyter lab
```

## Expected behavior

Filename to not be changed and "RTC:" prefix not showing in launcher tab.

## Context

- Operating System and version: MacOS Ventura 13.4 
- Browser and version: Edge 114.01823.82 
- JupyterLab version: 4.0.4 

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<img width="1733" alt="image" src="https://github.com/jupyterlab/jupyter-collaboration/assets/22301397/b2ae05d6-1fe8-486f-91b4-b96f952faa32">
</details>

**Comment by lrlunin** [comment]
I guess the same problem underlies [this bug in jupyterlab-h5web-viewer](https://github.com/silx-kit/jupyterlab-h5web/issues/121).

**Comment by f14h** [comment]
This also breaks the File->Export feature to download the notebook as pdf, html, latex, ... nbconvert does not find the file with the attached "RTC:"

**Comment by martinRenou** [comment]
This issue is not an issue with jupyter-collaboration, it is most likely `jupyter_scheduler` that does not support custom drives. Same comment for `jupyterlab-h5web` and the file export feature in core-jupyterlab.

You may see similar incompatibilities with https://github.com/jupyterlab-contrib/jupyterlab-filesystem-access or https://github.com/jupyterlab/jupyterlab-github which also provide custom drives.

**Comment by la0bing** [comment]
@martinRenou sorry I am not really familiar with the extension itself, what do you mean by custom drives here? As I just am using the docker stacks from jupyter as is with those 2 extra extensions, also weirdly when i remove the "RTC%3A" part from the url and reload the page, I am able to somehow workaround and use the scheduler as normal.
