### ISSUE TITLE
Opening two notebooks at the same time

### ISSUE THREAD

**Issue by asteppke** [jupyterlab/jupyter-collaboration#189]
For various purposes it would be great to open Jupyterlab on two browser tabs at the same time. 

According to this old request (https://github.com/jupyterlab/jupyterlab/issues/3853) the RTC feature makes this possible and was therefore closed.

When trying this feature out now Jupyterlab issues a warning: 
"Opening a document with multiple views simultaneously is not supported."

Can this be supported?

**Comment by hbcarlos** [comment]
Hi @asteppke, you should be able to open a notebook twice in different browser tabs.

What is not safe, is opening a notebook with different types of editors. For example, opening a notebook with the notebook editor and the plain text editor. See the screencast:

[Screencast from 2023-09-04 14-29-04.webm](https://github.com/jupyterlab/jupyter-collaboration/assets/26092748/5421eaab-60b9-4f71-b526-034a818d1462)

**Comment by asteppke** [comment]
Hi @hbcarlos 

Ah, thank you for that clarification. I have an idea now what is going on. The notebook in my test case is a coupled .ipynb/.py file using Jupytext. When copying and pasting the respective link (e.g. localhost:8888/lab/workspaces/auto-Y/tree/RTC%__.py) the second browser window wants to open this not as a notebook but as a .py file and then the warning pops up on both as this is using the plain text editor. 

Using the link for the .ipynb file works in two separate browser windows here fine. I'll ping the jupytext people in case they want to address this in the future.
