### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by frenzymadness** [jupyterlab/jupyter-collaboration#191]
Hello. Would it make sense to do a new release? In Fedora, I'd like to update the package from 1.0.0 to 1.1.0 but it's not possible because we already have jsonshcema 4.19.0 and collaboration 1.1.0 still ping jsonschema<4.18.0.

**Comment by hbcarlos** [comment]
Hi @frenzymadness.

There is a new pre-release, v1.2.0a0, with the changes you need. You can try it out with `pip install jupyter-collaboration --pre`.

Please try it out, let me know if it works for you, and I'll make the final release.

**Comment by jgeggatt** [comment]
I just tested the pre-release locally and it works as expected.  Mostly glad to see the "message-type: 1" server log messages disappear 🎉

**Comment by hbcarlos** [comment]
Thanks @jgeggatt.

Closing this issue with the new release [v1.2.0](https://github.com/jupyterlab/jupyter-collaboration/releases/tag/v1.2.0)
