### ISSUE TITLE
YDocExtension.document_save_delay conflicts with time.sleep

### ISSUE THREAD

**Issue by yambottle** [jupyterlab/jupyter-collaboration#192]
## Description

First time using this extension, it looks great. But I do find a conflict while I was testing 2 users edit the same `.ipynb` file

## Reproduce
1. Start jupyterlab server installed with jupyter-collaboration extension on localhost with all default configs
```
jupyter lab
```
3. Open up one regular chrome tab and an incognito chrome tab
4. Test `Untitiled.ipynb` file has only one cell:
```
import time
sec = 10
for i in range(sec):
    print(i)
    time.sleep(1) # this equals to the default `--YDocExtension.document_save_delay`
print("Done")
```
5. Execute this cell in one of the tab, it breaks while running and resets both tabs to its original state, no error showing in the jupyter server log. If I change the sleep time to 0.5 or 2, then this issue won't happen.
![Screen Capture_select-area_20230907142609](https://github.com/jupyterlab/jupyter-collaboration/assets/31813282/1d05340e-2139-414c-b4b8-c5f642390946)

## Expected behavior

Expect the cell should be successfully executed just like when time.sleep(0.5 or 2). If this is a known limitation, please mention this somewhere in the doc. 

## Context

- Operating System and version: Docker(tested in both Debian 12-slim and Alpine 3.18.3 base image)
- Browser and version: Version 113.0.5672.126 (Official Build) (64-bit)
- JupyterLab version: Version 4.0.5

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by hbcarlos** [comment]
Hi @yambottle.

This is fixed in the latest pre-release v2.0.0-alpha.2. You can try it out with
```
pip install jupyter-collaboration --pre
```
