### ISSUE TITLE
Images don't display

### ISSUE THREAD

**Issue by davidbrochart** [jupyterlab/jupyter-collaboration#229]
See https://github.com/jupyterlab/jupyter-collaboration/issues/162#issuecomment-1821349112.

## Description

In RTC images won't display.

## Reproduce

1. Install JupyterLab and jupyter-collaboration.
2. Open an image from the file browser.
3. See image not shown.

## Expected behavior

Images should be displayed.
[Jpterm](https://github.com/davidbrochart/jpterm) is able to show images using a [YBlob](https://github.com/jupyter-server/jupyter_ydoc/blob/bd998983bbf6b566bb0314faa48b8e51ba7747b6/jupyter_ydoc/yblob.py).

## Context

- Operating System and version: Linux Ubuntu 22.04
- JupyterLab version: 4.0.9
- jupyter-collaboration version: 2.0.0

**Comment by BwL1289** [comment]
Also experiencing this. With `jupyter-collaboration` installed, even if I'm not in an active collab session, the image gets uploaded with RTC.

**Comment by davidbrochart** [comment]
> With `jupyter-collaboration` installed, even if I'm not in an active collab session, the image gets uploaded with RTC.

What do you mean "the image gets uploaded"?

**Comment by BwL1289** [comment]
Apologies for the confusion. Should have said - "With jupyter-collaboration installed, even if I'm not in an active collab session, **and if i upload an image to jupyterlabs**, the image gets uploaded with RTC."

did that clarify?

**Comment by davidbrochart** [comment]
So your issue is not that double-clicking on an image in the file browser doesn't show the image? I don't really get what it means that the image gets uploaded with RTC.

**Comment by BwL1289** [comment]
Let me clarify. 

My issue, like yours, is that images don't display after I upload them and try to view them from the file browser. 

I was also commenting that even when I'm not in an active collaboration session, and I upload an image, the image is marked as being uploaded with RTC. See screenshot. Perhaps this is expected behavior. I'm not familiar enough with the framework to know.
![Screenshot 2024-01-04 at 12 44 03 PM](https://github.com/jupyterlab/jupyter-collaboration/assets/17219379/5138a53b-50d3-4365-8ceb-68792a8acb24)

**Comment by davidbrochart** [comment]
Oh I see now, thanks!
Yes the `RTC:` prefix in the path identifies the drive, but this is not the issue here.
The problem is that the frontend asks for a document of type `file`, which corresponds to a [YUnicode](https://github.com/jupyter-server/jupyter_ydoc/blob/bd998983bbf6b566bb0314faa48b8e51ba7747b6/jupyter_ydoc/yunicode.py) shared document, but this doesn't handle binary data. Instead, it should ask for a [YBlob](https://github.com/jupyter-server/jupyter_ydoc/blob/bd998983bbf6b566bb0314faa48b8e51ba7747b6/jupyter_ydoc/yblob.py).

**Comment by BwL1289** [comment]
Ack! Appreciate the clarification!

**Comment by davidbrochart** [comment]
It should be fixed in jupyter-collaboration v2.1.3.
