### ISSUE TITLE
Determine Python 3.8-3.9 support

### ISSUE THREAD

**Issue by dlqqq** [jupyterlab/jupyter-collaboration#248]
### Problem

The [source code](https://github.com/jupyterlab/jupyter-collaboration/pull/246/files#) currently uses a type declaration [syntax exclusive to Python 3.10+](https://peps.python.org/pep-0604/). We should work to:

1. Determine if Python 3.8 - 3.9 currently works with `jupyter_collaboration`,
2. Get consensus on whether we should support Python 3.8 - 3.9, and
3. Explicitly document the supported versions of Python for this project in the README and ReadTheDocs documentation.

**Comment by krassowski** [comment]
Even better would be ensuring a minimum required version is set in project.toml and using the maintainer tools action with dependencies: minimum option to run tests on both latest and newest supported versions :)

**Comment by davidbrochart** [comment]
`jupyter-collaboration` [supports Python 3.8 and above](https://github.com/jupyterlab/jupyter-collaboration/blob/8fee21f7cd338057c69febb5508f9b6c8bfd2392/pyproject.toml#L12). Union types as `X | Y` are allowed for python<3.10 with:
```py
from __future__ import annotations
```
