### ISSUE TITLE
Determine owner of the files in a given session

### ISSUE THREAD

**Issue by Liototo** [jupyterlab/jupyter-collaboration#301]
### Problem

Is there a way to quickly and reliably determine which of the users owns and shares the files?

### Additional context

As part of a Bachelor semester project, I'm developing a simple role system for jupyter-collaboration and I wish to implement an "Owner" role for the user who created and shared the working environment. Is that possible?

**Comment by davidbrochart** [comment]
I don't know what you mean by "owner of a file", that doesn't really make sense in a collaborative session, right?
But if your question is "who collaborates on a file", then the collaborators panel does that using the awareness, see [here](https://github.com/jupyterlab/jupyter-collaboration/blob/ebac5828d09087835d189db32d2bb1d5fcd7df27/packages/collaboration/src/collaboratorspanel.tsx#L80).

**Comment by Liototo** [comment]
Thank you for your response! I mean the user who creates and shares the session in the first place. My project is related to education and I'm trying to give specific capabilities to e.g. a teacher who shares a document for live coding demonstrations.

**Comment by davidbrochart** [comment]
It seems to me that what you need is managing permissions. Here are some pointers:
- Jupyter Server has support for [authorization](https://jupyter-server.readthedocs.io/en/latest/operators/security.html#authorization).
- Jupyverse supports a [multi-user scenario](https://jupyter-server.github.io/jupyverse/usage/multi_user).
- JupyterHub has [Role Based Access Control](https://jupyterhub.readthedocs.io/en/latest/rbac/index.html).

**Comment by Liototo** [comment]
I'll look into that then, thanks for your help!
