### ISSUE TITLE
Renaming a notebook results in a "File Changed" dialog

### ISSUE THREAD

**Issue by ibdafna** [jupyterlab/jupyter-collaboration#313]
Creating a new notebook, which defaults to `untitled.ipynb`, and hitting Command(Ctrl) + S to save it **for the first time** pops up a rename dialog. Renaming that notebook to anything other than the original name it had, results in "File Changed" dialog.

![rtc-save-error-dialog](https://github.com/jupyterlab/jupyter-collaboration/assets/24281433/1d617397-4f0f-4e65-8d4b-21b875358239)

**Comment by krassowski** [comment]
Similar to https://github.com/jupyterlab/jupyter-collaboration/issues/313
