### ISSUE TITLE
New alpha/beta release?

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyter-collaboration#325]
1. Should we publish a new pre-release since https://github.com/jupyterlab/jupyter-collaboration/pull/307 was merged?
2. Should we move to beta or are we waiting for any major new PRs?

CC @davidbrochart @fcollonval

**Comment by davidbrochart** [comment]
I think @martinRenou had an [issue with JupyterCAD](https://github.com/jupyterlab/jupyter-collaboration/issues/321#issuecomment-2202568082) using jupyter-collaboration v3.0.0a2, but otherwise we could release a beta?

**Comment by fcollonval** [comment]
I'm 👍 for moving to beta release

**Comment by krassowski** [comment]
Beta published, closing :tada:. For reference:
- https://github.com/jupyterlab/jupyter-collaboration/releases/tag/v3.0.0beta0
- https://pypi.org/project/jupyter-server-ydoc/1.0.0b0/
- https://pypi.org/project/jupyter-docprovider/1.0.0b0/
- https://pypi.org/project/jupyter-collaboration/3.0.0b0/
- https://pypi.org/project/jupyter-collaboration-ui/1.0.0b0/

**Comment by krassowski** [comment]
Releasing a new beta to include the recent fixes.
