### ISSUE TITLE
Final v3.0.0 release

### ISSUE THREAD

**Issue by davidbrochart** [jupyterlab/jupyter-collaboration#354]
It seems to me that we could release jupyter-collaboration v3.0.0. I installed v3.0.0b3 and it works fine with JupyterLab v4.2.5. Or should we make another pre-release that includes the timeline?

**Comment by davidbrochart** [comment]
What do you think about including #353?

**Comment by jtpio** [comment]
> Or should we make another pre-release that includes the timeline?

Is the timeline opt-in? Or can it be collapsed? Thinking it might take quite some space in the status bar, according to the screencast in the blog post: https://blog.jupyter.org/exploring-a-documents-timeline-in-jupyterlab-6084f96db263

If so, it could be useful to mention it in the docs: https://jupyterlab-realtime-collaboration.readthedocs.io/en/latest/

**Comment by davidbrochart** [comment]
> Is the timeline opt-in?

It's not opt-in, but if you don't use it then no slider is shown, only this icon:
![image](https://github.com/user-attachments/assets/3c0cb408-988c-4c86-9591-b8c3e4b40f80)

**Comment by krassowski** [comment]
I think we should sync it with JupyterLab 4.3.0 final. I think we do not have to wait for https://github.com/jupyterlab/jupyter-collaboration/pull/345 but it would be lovely to include it if we can.

**Comment by davidbrochart** [comment]
> I think we should sync it with JupyterLab 4.3.0 final.

When do you see this happening?

**Comment by krassowski** [comment]
One week after RC gets published assuming no new blockers

**Comment by davidbrochart** [comment]
> I think we should sync it with JupyterLab 4.3.0 final.

But why does it need to be synced, since it works with JupyterLab 4.2.5?

**Comment by krassowski** [comment]
Ah, the dependency is the other way round. JupyterLab 4.3 requires the new collaboration packages to have lifted ydoc version pin, right? In that case I guess it does not need to wait :)

**Comment by davidbrochart** [comment]
> JupyterLab 4.3 requires the new collaboration packages to have lifted ydoc version pin, right?

Yes. I just tried jupyter-collaboration v3.0.0b4 with JupyterCAD, everything seems to work fine.
I'd like to have #345 in before the final release, it will allow to swap jupyter-collaboration with [jupyter-shared-drive](https://github.com/davidbrochart/jupyter-shared-drive) (or any other collaboration system that implements the `ICollaborativeDrive`), and have support for JupyterLite.

**Comment by krassowski** [comment]
So we are good to release final, right?

**Comment by davidbrochart** [comment]
There is still #353 that would be good to get in before v3. If it's merged after v3 that would be another breaking change. I'll rebase it.

**Comment by davidbrochart** [comment]
I just release v3.0.0beta8 which has #353, everything seems to work fine.
I guess we are good to release v3.0.0 final?

**Comment by davidbrochart** [comment]
One thing I noticed is that when creating a new notebook, no empty cell is created, even though https://github.com/jupyterlab/jupyterlab/pull/16732 was not merged yet. It might be because of https://github.com/jupyter-server/jupyter_ydoc/pull/266, but I thought this was not enough and the frontend added an empty cell if there was no cell.

**Comment by davidbrochart** [comment]
I think we should merge https://github.com/jupyterlab/jupyterlab/pull/16732 and have https://github.com/jupyter-server/jupyter_ydoc/pull/266 enabled when `allowEmptyNotebook` is true.

**Comment by davidbrochart** [comment]
I'm planning to release v3 soon, if there are no objections.

**Comment by davidbrochart** [comment]
I reverted https://github.com/jupyter-server/jupyter_ydoc/pull/266 in https://github.com/jupyter-server/jupyter_ydoc/pull/280.
I don't see any blocker to release jupyter-collaboration v3.0.0 final. I'll do it today or tomorrow, please let me know if you have any objection.

**Comment by davidbrochart** [comment]
Hmm `prep_release` [failed](https://github.com/jupyterlab/jupyter-collaboration/actions/runs/11400554360/job/31721639328). Could it be due to #343 @brichet?

**Comment by jtpio** [comment]
Did you specify the correct version spec? https://github.com/jupyterlab/jupyter-collaboration/blob/main/RELEASE.md#version-specification

**Comment by davidbrochart** [comment]
Oh I was not aware of this, I just specified `3.0.0` and thought it would work.
It seems I could use `release` but it means we need to make an `rc` before?

**Comment by jtpio** [comment]
yeah it's also a good practice to make an `rc` first.

**Comment by jtpio** [comment]
But then it can be weird to do the final release right after. Maybe do it on Monday to give the `rc` a few days? (or at least the weekend).

When you do the final release, check this box so the changelog is correctly populated:

![image](https://github.com/user-attachments/assets/a0492000-0106-4de0-ac7a-98e1dea95b0b)

**Comment by davidbrochart** [comment]
OK, let's release v3.0.0 final next week. I just released v3.0.0rc0.

**Comment by davidbrochart** [comment]
Since #379 seems to target v3.1.0, should we release v3.0.0 now?

**Comment by jtpio** [comment]
Similar to this JupyterLab 4.3.0 (blocker) issue: https://github.com/jupyterlab/jupyterlab/issues/16649

Are you fine to depend on an alpha release of `@jupyter/ydoc`? 

https://github.com/jupyterlab/jupyter-collaboration/blob/b64b54bcdda18026d8571bf7ef61fb5946cfbf7f/packages/collaborative-drive/package.json#L40

**Comment by davidbrochart** [comment]
We could release `@jupyter/ydoc` v3.0.0 before, and update the dependency here?

**Comment by jtpio** [comment]
Yes, but from the discussion in https://github.com/jupyter-server/jupyter_ydoc/issues/281, there seems to be one more issue to be fixed in `jupyter_ydoc` first before: https://github.com/jupyter-server/jupyter_ydoc/issues/269

**Comment by davidbrochart** [comment]
Ah yes I forgot.
