### ISSUE TITLE
New branch: `suggestions`

### ISSUE THREAD

**Issue by davidbrochart** [jupyterlab/jupyter-collaboration#387]
I would like to create a new branch, maybe called `suggestions`, where we would implement new features for the suggestion system. The first PR against this new branch could be:
- #382

This is to be able to work freely while not blocking any release of jupyter-collaboration, and to iron out the details as we figure them out. Please let me know if there are objections.

**Comment by davidbrochart** [comment]
Now that jupyter-collaboration v3.0.0 is out, maybe we should instead create a `3.0.0` branch and instead commit the suggestion system work in `main`?

**Comment by jtpio** [comment]
Not sure, maybe it's more convenient if `main` is used for releasing `3.0.x` and future `3.1.x`, since it's not clear how fast the suggestions system will stabilize? (avoid too many backports).

**Comment by davidbrochart** [comment]
Yes, maybe the suggestion system should target v4 then, and we should create a `4.0.0` branch?

**Comment by jtpio** [comment]
In that case, maybe it's fine to keep the `suggestions` branch for now, and we create the `4.0.0` branch when needed and when we have more visibility?

**Comment by davidbrochart** [comment]
Yes, the only thing is if @trungleduc needs pre-releases to ease his work in JupyterCAD. I was thinking that we could pre-release v4.

**Comment by jtpio** [comment]
Right, having a way to make pre-releases would be useful.

But do we already know if the work on suggestions will require a major release? Or will it be additive without breaking changes, so it could be made available in a `3.x` minor release?

**Comment by trungleduc** [comment]
with the eventual update related to the Websocket handler, I'm fine working with the PRs.

**Comment by trungleduc** [comment]
Hi all, the `suggestions` branch is not created yet?

**Comment by davidbrochart** [comment]
Hmm didn't you said that you were fine working with PRs?

**Comment by davidbrochart** [comment]
No you're right, I'll create the `suggestions` branch and merge #382.

**Comment by trungleduc** [comment]
Great! Thanks
