### ISSUE TITLE
File browser delays from Jupyter collaborations file browser

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyter-collaboration#406]
## Description

When Jupyter collaboration is installed (even if disabled) it uses a different doc provider and file browser extension. When this file browser is active, there is a 10 second delay when a user uploads a file to the file browser. When you uninstall `jupyter-collaboration` or disable its file browser the issue resolves.

## Reproduce

With `jupyter-collaboration` installed, drag an external file to the file browser to upload. You will see a 10 second delay before the file appears.

## Expected behavior

In JupyterLab master, a file browser refresh is triggered after a file upload completes, so it is visible immediately.

**Comment by davidbrochart** [comment]
The issue not only happens when uploading a file, but also when creating a new file or notebook.
I opened https://github.com/jupyterlab/jupyterlab/pull/16988.
