### ISSUE TITLE
Renaming a file eventually raises an JS exception

### ISSUE THREAD

**Issue by martinRenou** [jupyterlab/jupyter-collaboration#411]
## Description

The error seems to occur here:

https://github.com/jupyterlab/jupyter-collaboration/blob/main/packages/docprovider/src/ydrive.ts#L209

https://github.com/user-attachments/assets/2412a159-17bd-46c1-8b07-2093508889ec

## Reproduce

1. Create a notebook
2. Rename it
3. See an error occur in the js console

**Comment by krassowski** [comment]
Hmm... the question becomes how we could get the current file path in:

https://github.com/jupyterlab/jupyter-collaboration/blob/5079613a1ed9ad888c9e776a425c5f9285952f4d/packages/docprovider/src/ydrive.ts#L160-L209

It looks like `YDocument` does not have it. We could either try to get it from fileid on the server (but that would be possibly slow?) or find a way to access it from the frontend.

**Comment by davidbrochart** [comment]
The path is accessible from a shared document (in `state.path`). I opened #413.

**Comment by krassowski** [comment]
Ah, I did not see it because state is typed as just a JSON Object:

https://github.com/jupyter-server/jupyter_ydoc/blob/c9525f100d23cdac9d48c29805091f7730e5a600/javascript/src/ydocument.ts#L87-L92

Where is the state set? Could we narrow the types down possibly?

**Comment by davidbrochart** [comment]
> Where is the state set?

Here:
https://github.com/jupyterlab/jupyter-collaboration/blob/2e3cf4acc08eba03d3558a0792399ee6d38a7453/projects/jupyter-server-ydoc/jupyter_server_ydoc/rooms.py#L229-L233

> Could we narrow the types down possibly?

In jupyter-ydoc, probably yes.

**Comment by martinRenou** [comment]
Thanks!
